image:
  file: .gitpod.Dockerfile

tasks:
  - name: Start Airflow
    command: |
      # Prepare Airflow home & config
      mkdir -p ./airflow ./airflow/dags
      touch ./airflow/airflow.cfg

      # Link your repo DAGs into AIRFLOW_HOME
      ln -sf $PWD/dags/* $PWD/airflow/dags/

      # Export environment variables
      export AIRFLOW_HOME=$PWD/airflow
      export AIRFLOW_CONFIG=$AIRFLOW_HOME/airflow.cfg
      export AIRFLOW__CORE__DAGS_FOLDER=$PWD/dags
      export AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////$AIRFLOW_HOME/airflow.db

      # Start Airflow (DB init + webserver + scheduler)
      airflow standalone

ports:
  - port: 8080
    onOpen: open-preview
