image:
  file: .gitpod.Dockerfile

tasks:
  - name: Start Airflow
    command: |
      # ensure our local airflow folder exists and is owned by gitpod
      mkdir -p ./airflow
      export AIRFLOW_HOME=$PWD/airflow
      export AIRFLOW_CONFIG=$AIRFLOW_HOME/airflow.cfg
      export AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////${AIRFLOW_HOME}/airflow.db
      airflow standalone

ports:
  - port: 8080
    onOpen: open-preview
