image:
  file: .gitpod.Dockerfile

tasks:
  - name: Start Airflow
    command: |
      # Prepare Airflow home & DAGs
      mkdir -p ./airflow ./airflow/dags
      touch ./airflow/airflow.cfg
      ln -sf $PWD/dags/* ./airflow/dags/

      # Export environment variables
      export AIRFLOW_HOME=$PWD/airflow
      export AIRFLOW_CONFIG=$AIRFLOW_HOME/airflow.cfg
      export AIRFLOW__CORE__DAGS_FOLDER=$PWD/dags
      export AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////$AIRFLOW_HOME/airflow.db
      export AIRFLOW__API_AUTH__JWT_SECRET=my_super_secret_key

      # Ensure Python can import your include/ package
      export PYTHONPATH=$PYTHONPATH:$PWD

      # Launch Airflow 3 in standalone mode
      airflow standalone

ports:
  - port: 8080
    onOpen: open-preview
