image:
  file: .gitpod.Dockerfile

tasks:
  - name: Start Airflow
    command: |
      export AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////tmp/airflow.db
      airflow standalone

ports:
  - port: 8080
    onOpen: open-preview
