image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      pip install --upgrade pip
      airflow db init
      airflow users create \
        --username admin \
        --firstname First \
        --lastname Last \
        --role Admin \
        --email admin@example.com \
        --password admin
  - command: |
      airflow scheduler & airflow webserver

ports:
  - port: 8080
    onOpen: open-preview
